---
title: "Analysis of DEG from edgeR data (Leperchio 2021 method)"
output: html_notebook
---

## Packages
```{r}
library(tidyverse)
library(readxl)
library(qvalue)
```

## Load edgeR differential expression data
```{r}
list.files(path = "../data/edgeR", pattern = "csv", full.names = T)

n2_egl9_edger <- read_csv("../data/edgeR/egl9_vs_N2cgc_WS245_Apr_28_2016.csv") %>% 
  rename(Gene = `...1`, 
         padj = FDR,
         pvalue = PValue) %>% 
  column_to_rownames("Gene")

n2_or3350_edger <- read_csv("../data/edgeR/OR3350_vs_N2cgc_WS245_Apr_28_2016.csv") %>% 
  rename(Gene = `...1`, 
         padj = FDR,
         pvalue = PValue) %>% 
  column_to_rownames("Gene")

egl9hif1_egl9_edger <- read_csv("../data/edgeR/egl9_vs_egl9hif1_WS245_Apr_28_2016.csv") %>% 
  rename(Gene = `...1`, 
         padj = FDR,
         pvalue = PValue) %>% 
  column_to_rownames("Gene")

egl9hif1_or3350_edger <- read_csv("../data/edgeR/OR3350_vs_egl9hif1_WS245_Apr_28_2016.csv") %>% 
  rename(Gene = `...1`, 
         padj = FDR,
         pvalue = PValue) %>% 
  column_to_rownames("Gene")
```


```{r}
### This code chunk was provided by Drs. Leandros Boukas and Kasper Hansen as part of the analyses in Luperchio et al., eLife 2021

###In the following we assume we already have the results objects from the differential analyses of two experiments. 
###One object is res_exp1 and the other is res_exp2. We assume that we have well-calibrated p-value distributions, 
###and the results objects are in the format provided by edgeR
###

res_exp1 <- n2_egl9_edger
res_exp2 <- n2_or3350_edger

##First, to visually get a feel for the overlap between the differential hits, look at the conditional p-value distributions
hist(res_exp2$pvalue[which(rownames(res_exp2) %in% rownames(res_exp1)[which(res_exp1$padj < 0.01)])], 
     breaks = 40, freq = FALSE)
hist(res_exp2$pvalue[-which(rownames(res_exp2) %in% rownames(res_exp1)[which(res_exp1$padj < 0.01)])], 
     breaks = 40, freq = FALSE)


##now use the qvalue package to estimate pi_0 and label genes as shared differential at the desired fdr level
# library(qvalue)

qobj <- qvalue(p = res_exp2$pvalue[which(rownames(res_exp2) %in% rownames(res_exp1)[which(res_exp1$padj < 0.01)])], 
                                        fdr.level = 0.01, pi0.method = "bootstrap")

#note: it is possible for the estimated pi_0 to be discordant (bigger or smaller) with what we intuitively expect 
#based on the p-val distributions. In this case, look at the pi_0 values produced for different values of the lambda parameter

shared_differential_genes <- res_exp2[which(rownames(res_exp2) %in% 
                                             rownames(res_exp1)[which(res_exp1$padj < 0.01)])[
                                                          which(qobj$significant == TRUE)], ]

##get a p-value for the overlap via permutations
# null_distribution <- replicate(10000, {
#   pi0_random <- pi0est(p = sample(res_exp2$pvalue, 
#                                   length(which(rownames(res_exp2) %in% rownames(res_exp1)[which(res_exp1$padj < 0.01)]))), 
#                        pi0.method = "bootstrap")$pi0
#   1- pi0_random
# })

(shared_differential_genes_n2 <- shared_differential_genes)
# hist(null_distribution)
```

```{r}
### This code chunk was provided by Drs. Leandros Boukas and Kasper Hansen as part of the analyses in Luperchio et al., eLife 2021

###In the following we assume we already have the results objects from the differential analyses of two experiments. 
###One object is res_exp1 and the other is res_exp2. We assume that we have well-calibrated p-value distributions, 
###and the results objects are in the format provided by edgeR
###

res_exp1 <- egl9hif1_egl9_edger
res_exp2 <- egl9hif1_or3350_edger

##First, to visually get a feel for the overlap between the differential hits, look at the conditional p-value distributions
hist(res_exp2$pvalue[which(rownames(res_exp2) %in% rownames(res_exp1)[which(res_exp1$padj < 0.01)])], 
     breaks = 40, freq = FALSE)
hist(res_exp2$pvalue[-which(rownames(res_exp2) %in% rownames(res_exp1)[which(res_exp1$padj < 0.01)])], 
     breaks = 40, freq = FALSE)


##now use the qvalue package to estimate pi_0 and label genes as shared differential at the desired fdr level
# library(qvalue)

qobj <- qvalue(p = res_exp2$pvalue[which(rownames(res_exp2) %in% rownames(res_exp1)[which(res_exp1$padj < 0.01)])], 
                                        fdr.level = 0.01, pi0.method = "bootstrap")

#note: it is possible for the estimated pi_0 to be discordant (bigger or smaller) with what we intuitively expect 
#based on the p-val distributions. In this case, look at the pi_0 values produced for different values of the lambda parameter

shared_differential_genes <- res_exp2[which(rownames(res_exp2) %in% 
                                             rownames(res_exp1)[which(res_exp1$padj < 0.01)])[
                                                          which(qobj$significant == TRUE)], ]

##get a p-value for the overlap via permutations
# null_distribution <- replicate(10000, {
#   pi0_random <- pi0est(p = sample(res_exp2$pvalue, 
#                                   length(which(rownames(res_exp2) %in% rownames(res_exp1)[which(res_exp1$padj < 0.01)]))), 
#                        pi0.method = "bootstrap")$pi0
#   1- pi0_random
# })

(shared_differential_genes_egl9hif1 <- shared_differential_genes)
# hist(null_distribution)
```

```{r}
# List of genes that are significantly altered in each individual comparison

egl9hif1_egl9_edger %>%
  as_tibble(rownames = "Gene") %>%
  filter(padj <= 0.01)

egl9hif1_or3350_edger %>%
  as_tibble(rownames = "Gene") %>%
  filter(padj <= 0.01)

n2_egl9_edger %>%
  as_tibble(rownames = "Gene") %>%
  filter(padj <= 0.01)

n2_or3350_edger %>%
  as_tibble(rownames = "Gene") %>%
  filter(padj <= 0.01)
```

```{r}
# Shared differentially expressed genes using Luperchio et al. method for each of the paired comparisons.

shared_differential_genes_n2
shared_differential_genes_egl9hif1

shared_differential_genes_n2 %>%
  as_tibble(rownames = "Gene") %>% 
  write_csv(file = "../output/tables/shared_differential_genes_edgeR_n2.csv")

shared_differential_genes_egl9hif1 %>%
  as_tibble(rownames = "Gene") %>% 
  write_csv(file = "../output/tables/shared_differential_genes_edgeR_egl9hif1.csv")

```


```{r}
# Generate final list of shared genes across all four comparisons based on overlap of the two paired shared gene lists

final_shared_genes <- intersect(shared_differential_genes_n2 %>% rownames(),
          shared_differential_genes_egl9hif1 %>% rownames())

final_unalterd_genes <- setdiff(rownames(n2_egl9_edger), final_shared_genes)

final_table_for_BETA <- tibble(Gene = c(final_shared_genes, final_unalterd_genes),
                               pvalue = rep(c(0.01, 1), times = c(length(final_shared_genes), length(final_unalterd_genes))))


write_csv(final_table_for_BETA, file = "../output/tables/shared_differential_genes_edgeR_for_BETA.csv")
```

